/* Generated by wayland-scanner 1.20.92 */

/*
 * Copyright © 2013-2016 Collabora, Ltd.
 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif


static const struct wl_interface *louvre_dock_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
};

static const struct wl_message dock_requests[] = {
	{ "destroy", "", louvre_dock_types + 0 },
	{ "test", "ffff", louvre_dock_types + 0 },
};

WL_PRIVATE const struct wl_interface dock_interface = {
	"dock", 1,
	2, dock_requests,
	0, NULL,
};

