/* Generated by wayland-scanner 1.20.92 */

#ifndef LOUVRE_DOCK_SERVER_PROTOCOL_H
#define LOUVRE_DOCK_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_louvre_dock The louvre_dock protocol
 * @section page_ifaces_louvre_dock Interfaces
 * - @subpage page_iface_dock - Bla bla bla...
 * @section page_copyright_louvre_dock Copyright
 * <pre>
 *
 * Copyright © 2013-2016 Collabora, Ltd.
 * </pre>
 */
struct dock;

#ifndef DOCK_INTERFACE
#define DOCK_INTERFACE
/**
 * @page page_iface_dock dock
 * @section page_iface_dock_desc Description
 *
 * Bla bla bla...
 * @section page_iface_dock_api API
 * See @ref iface_dock.
 */
/**
 * @defgroup iface_dock The dock interface
 *
 * Bla bla bla...
 */
extern const struct wl_interface dock_interface;
#endif

/**
 * @ingroup iface_dock
 * @struct dock_interface
 */
struct dock_interface {
	/**
	 * Bla bla bla...
	 *
	 * Bla bla bla...
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 * Bla bla bla...
	 *
	 * Bla bla bla...
	 * @param x x
	 * @param y y
	 * @param width width
	 * @param height height
	 */
	void (*test)(struct wl_client *client,
		     struct wl_resource *resource,
		     wl_fixed_t x,
		     wl_fixed_t y,
		     wl_fixed_t width,
		     wl_fixed_t height);
};


/**
 * @ingroup iface_dock
 */
#define DOCK_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_dock
 */
#define DOCK_TEST_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
